### ISSUE TITLE
Question, not an issue about using this fixture in seperate class

### ISSUE THREAD

**Issue by johnkattenhorn** [davetimmins/serilog-sinks-xunittestoutput#7]
I really appreciate this simple fixture, just what I needed. I was wondering though, why would this fixture not work if it's contained in a separate assembly to the tests.

All the references look good, local copy = true, is this something that is not support by XUnit does anyone know ?

**Comment by davetimmins** [comment]
Does this help? https://github.com/xunit/xunit/issues/374

**Comment by johnkattenhorn** [comment]
Thanks @davetimmins - Yep I was try to use the unsupported method.
